Add tests for chat app.
MetalMari/chat_grpc pull request #6
Opened 2022-03-03 10:24 UTC by MetalMari

2022-03-03 12:24 UTC, mmishche requested changes

2022-03-03 12:24 UTC, mmishche commented on tests/test_chat_storage.py
> +        """Tests create user method."""
I'd rather change docstring to  `"""Tests 'create_user' method."""` which contains the method name clearly

2022-03-03 12:24 UTC, mmishche commented on tests/test_chat_storage.py
> +        """Tests users list method."""
The same as above

2022-03-03 12:24 UTC, mmishche commented on tests/test_chat_storage.py
> +        self.assertListEqual(expected, messages)
Also, you might check that get_prefix was called with some arguments, in that way we ensure the method is given with correct prefix

2022-03-03 12:24 UTC, mmishche commented on tests/test_chat_storage.py
> +        self.assertEqual(key, expected_key)
The method that does assertion should receive the first argument as expected one and the second be actual

2022-03-03 12:24 UTC, mmishche commented on tests/test_chat_storage.py
> +        self.assertEqual(key, expected_key)
the same as above

2022-03-03 22:16 UTC, MetalMari commented on tests/test_chat_storage.py
> +        """Tests create user method."""
Done

2022-03-03 22:17 UTC, MetalMari commented on tests/test_chat_storage.py
> +        self.assertListEqual(expected, messages)
Checking was added

2022-03-07 10:06 UTC, mmishche requested changes

2022-03-07 10:06 UTC, mmishche commented on tests/test_chat_client.py
> +        chat_pb2.GetUsersRequest = mock.Mock()
you don't need to mock it

2022-03-07 10:06 UTC, mmishche commented on tests/test_chat_client.py
> +        stub.GetUsers = mock.Mock()
Mocking some instance with defining other mocks within it is clearier to understand 
```suggestion
        stub = mock.Mock(
            GetUsers=mock.Mock()
        )
```

2022-03-07 10:06 UTC, mmishche commented on tests/test_chat_client.py
> +        stub.GetUsers.assert_called()
Also, you should assert that it was called with the specific count of times and with or without arguments, try to use another method here

2022-03-07 11:44 UTC, MetalMari commented on tests/test_chat_client.py
> +        self.assertTrue(mock_get_users_list.called)
Thanks, have changed it.

2022-03-07 11:44 UTC, MetalMari commented on tests/test_chat_client.py
> +                          lambda: chat_client.subscribe_data_valid_or_raiserror(args))
Thanks, have changed it.

2022-03-07 11:48 UTC, MetalMari commented on tests/test_chat_client.py
> +        stub.GetUsers.assert_called()
Thanks, changed method call, added args.

2022-03-08 13:59 UTC, mmishche requested changes

2022-03-08 13:59 UTC, mmishche commented on tests/test_chat_client.py
> +        stub.Subscribe.return_value = ["message1", "message2", "message3"]
I believe you can use the following format:
```suggestion
        stub = mock.Mock(
            Subscribe=mock.Mock(
                return_value=["message1", "message2", "message3"]
             )
         )
```

2022-03-08 13:59 UTC, mmishche commented on tests/test_chat_server.py
> +        cls.chat = chat_server.Chat(cls.storage)
Please define these attributes in the setUp method, because setUpClass attributes define only one time during class initialization. What can be happened if you use it here? Let's imagine that your storage client will be called multiple times during your TestChat, so if you want to assert that it will be called only one time in some test you couldn't and it will raise an error

2022-03-08 13:59 UTC, mmishche commented on tests/test_chat_server.py
> +        context = mock.Mock()
I believe you might not define this variable, and may set it as a argument

2022-03-08 13:59 UTC, mmishche commented on tests/test_chat_server.py
> +        self.storage.delete_user_message = mock.Mock()
the same as above

2022-03-08 13:59 UTC, mmishche commented on tests/test_chat_server.py
> +                                     body=message.body) for message in messages]
don't do that, just define the list manually as expected.
it will be better to test how many times 'get_user_messages' was called and what arguments were passed

2022-03-09 09:10 UTC, MetalMari commented on chat/chat_server.py
> +from chat import chat_storage
In the way "import chat_storage", the tests don't run correctly

2022-03-09 09:16 UTC, MetalMari commented on tests/test_chat_server.py
> +        cls.chat = chat_server.Chat(cls.storage)
Changed it

2022-03-09 09:26 UTC, MetalMari commented on tests/test_chat_server.py
> +        context = mock.Mock()
Done

2022-03-09 09:32 UTC, MetalMari commented on tests/test_chat_server.py
> +                                     body=message.body) for message in messages]
Done

2022-03-24 09:58 UTC, merged